package idc.aast.edu.webservice;

//----------------------------------------------------
//
// Generated by www.easywsdl.com
// Version: 4.1.1.0
//
// Created by Quasar Development at 04-12-2014
//
//---------------------------------------------------



public class STDWEBOperationResult< T>
{
    public java.lang.Exception Exception;
    public T Result;
    public java.lang.Object Tag;
    public java.lang.String MethodName;
}
