package idc.aast.edu.webservice;

//----------------------------------------------------
//
// Generated by www.easywsdl.com
// Version: 4.1.1.0
//
// Created by Quasar Development at 04-12-2014
//
//---------------------------------------------------



public interface STDWEBIServiceEvents
{
    public void Starting();
    public void Completed(STDWEBOperationResult result);
}
